TEMPLATE = subdirs

message("PYMESHLAB_DISTRIB_DIRECTORY: "$$MESHLAB_DISTRIB_DIRECTORY)
message("PYMESHLAB_DISTRIB_PLUGINS_DIRECTORY: "$$MESHLAB_DISTRIB_PLUGINS_DIRECTORY)

SUBDIRS = \ #sub projects names
	$$PYMESHLAB_BASE_DIRECTORY/meshlab/src/common
