# must use ubuntu:22.04 for qt 5.15
FROM --platform=linux/aarch64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive 

ARG USERNAME=pymeshlab
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ARG PYTHON_VERSION=3.11

ENV LD_LIBRARY_PATH=/workspaces/pymeshlab/pymeshlab/lib/

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    build-essential \
    fontconfig \
    fuse \
    gdb \
    git \
    kmod \
    libboost-dev \
    libdbus-1-3 \
    libegl-dev \
    libfuse2 \
    libgmp-dev \
    libglu1-mesa-dev \
    libmpfr-dev \
    libpulse-mainloop-glib0 \
    libtbb-dev \
    libxerces-c-dev \
    patchelf \
    qtbase5-dev \
    qt5-qmake \
    rsync \
    # to be removed
    unzip \
    wget

# install python
RUN apt-get -y install software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && apt-get -y update && \
    apt-get -y install python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-distutils && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python${PYTHON_VERSION} get-pip.py && \
    rm get-pip.py && \
    pip install numpy

# install latest cmake and embree
RUN apt-get -y purge --auto-remove cmake && \
    wget -qO- "https://cmake.org/files/v3.19/cmake-3.19.3-Linux-aarch64.tar.gz" \
    | tar --strip-components=1 -xz -C /usr/local &&\
    # wget -qO- "https://github.com/embree/embree/releases/download/v4.3.2/embree-4.3.2.x86_64.linux.tar.gz" \
    # | tar -xz -C /usr/local && \
    # bash /usr/local/embree-vars.sh  && \
    wget -q "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux-aarch64.zip" && \
    unzip -o ninja-linux-aarch64.zip  -d /usr/bin/ && \
    rm ninja-linux-aarch64.zip && \
    chmod +x /usr/bin/ninja && \
    apt-get -y remove wget unzip && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

# Generating a universally unique ID for the Container
RUN  dbus-uuidgen > /etc/machine-id

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    # [Optional] Add sudo support.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME